services:
  - type: web
    name: mandal-downloader
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update -y && apt-get install -y ffmpeg
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
